"""add leaderboard entries

Revision ID: 1fe05c553bc2
Revises: 4c155f9b43d4
Create Date: 2026-09-07 18:01:24.187189
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fe05c553bc2'
down_revision: Union[str, None] = '4c155f9b43d4'
branch_labels: Union[str, Sequence[str] | None] = None
depends_on: Union[str, Sequence[str] | None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_entries',
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('league', sa.String(length=32), nullable=False),
    sa.Column('weekly_xp', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_entries_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_entries_week_start'))

    op.drop_table('leaderboard_entries')
    # ### end Alembic commands ###
