"""initial schema

Revision ID: 4c155f9b43d4
Revises: 
Create Date: 2026-09-07 17:56:14.472934
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4c155f9b43d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str] | None] = None
depends_on: Union[str, Sequence[str] | None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flag_icon', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('hearts', sa.Integer(), nullable=False),
    sa.Column('max_hearts', sa.Integer(), nullable=False),
    sa.Column('hearts_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('gems >= 0', name='ck_users_gems_non_negative'),
    sa.CheckConstraint('hearts <= max_hearts', name='ck_users_hearts_lte_max'),
    sa.CheckConstraint('hearts >= 0', name='ck_users_hearts_non_negative'),
    sa.CheckConstraint('streak >= 0', name='ck_users_streak_non_negative'),
    sa.CheckConstraint('xp >= 0', name='ck_users_xp_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('units',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_color', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'order_index', name='uq_units_course_order')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_course_id'), ['course_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_activity_daily')
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_user_id'), ['user_id'], unique=False)

    op.create_table('xp_transactions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reason', 'reference_type', 'reference_id', name='uq_xp_transaction_idempotent')
    )
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('skills',
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('total_levels', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'order_index', name='uq_skills_unit_order')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_unit_id'), ['unit_id'], unique=False)

    op.create_table('lessons',
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('xp_reward >= 0', name='ck_lessons_xp_reward_non_negative'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'order_index', name='uq_lessons_skill_order')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_skill_id'), ['skill_id'], unique=False)

    op.create_table('user_skill_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('level >= 1', name='ck_usp_level_min'),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='ck_usp_progress_range'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill_progress')
    )
    with op.batch_alter_table('user_skill_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skill_progress_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_skill_progress_user_id'), ['user_id'], unique=False)

    op.create_table('exercises',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('question_audio_url', sa.String(length=500), nullable=True),
    sa.Column('exercise_data', sa.JSON(), nullable=True),
    sa.Column('validation_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_exercises_lesson_order')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('lesson_attempts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_exercise_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('hearts_lost', sa.Integer(), nullable=False),
    sa.Column('completion_result', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_attempts_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_attempts',
    sa.Column('lesson_attempt_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('submitted_answer', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_attempt_id'], ['lesson_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_attempt_id', 'exercise_id', 'attempt_number', name='uq_exercise_attempt_number')
    )
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_attempts_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_attempts_lesson_attempt_id'), ['lesson_attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_attempts_lesson_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_attempts_exercise_id'))

    op.drop_table('exercise_attempts')
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_lesson_attempts_lesson_id'))

    op.drop_table('lesson_attempts')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_lesson_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('user_skill_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skill_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_skill_progress_skill_id'))

    op.drop_table('user_skill_progress')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_skill_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_unit_id'))

    op.drop_table('skills')
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_transactions_user_id'))

    op.drop_table('xp_transactions')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_activity_date'))

    op.drop_table('user_activity')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievements_achievement_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_course_id'))

    op.drop_table('units')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('courses')
    op.drop_table('achievements')
    # ### end Alembic commands ###
